// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT21DL0iIR_MX3FWPL5hqacTLcb8mvV-c',
    appId: '1:460099355417:web:4a5ef071c0725f4639fb88',
    messagingSenderId: '460099355417',
    projectId: 'maqam-e74e3',
    authDomain: 'maqam-e74e3.firebaseapp.com',
    storageBucket: 'maqam-e74e3.appspot.com',
    measurementId: 'G-9GW18M5ZM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1_D5SSzUfZ7bjiU1LYwQepIASL2cTlgc',
    appId: '1:460099355417:android:45848d2874f4820439fb88',
    messagingSenderId: '460099355417',
    projectId: 'maqam-e74e3',
    storageBucket: 'maqam-e74e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFmCGqfQnCgrTUNlLF6KrgVBXACd5dTKg',
    appId: '1:460099355417:ios:42dda7840608fe3539fb88',
    messagingSenderId: '460099355417',
    projectId: 'maqam-e74e3',
    storageBucket: 'maqam-e74e3.appspot.com',
    iosBundleId: 'com.example.maqam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFmCGqfQnCgrTUNlLF6KrgVBXACd5dTKg',
    appId: '1:460099355417:ios:93465ac40c7decc339fb88',
    messagingSenderId: '460099355417',
    projectId: 'maqam-e74e3',
    storageBucket: 'maqam-e74e3.appspot.com',
    iosBundleId: 'com.example.maqam.RunnerTests',
  );
}
